[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"

solc = "0.8.33"
optimizer = true
optimizer_runs = 200
via-ir = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

